import { useEffect, useState } from "react";
import { activateSupporterLicense, getPreferences, getSupporterStatus, listenDesktopEvents } from "../lib/bridge";
import { normalizeLanguage } from "../lib/i18n";
import type { Language, SupporterStatus, WidgetSkin } from "../types";
import logoUrl from "../../assets/quota-float-logo.svg";
import blurThumbnailUrl from "../../assets/blur-thumbnail.svg";
import likeIconUrl from "../../assets/点赞.svg";

const labels = { "zh-CN": { title: "支持者皮肤", description: "购买支持者皮肤，是对开发者持续完善 Quota Float、制作更多皮肤和实用小工具的支持。选择想购买的皮肤，复制设备码发送给开发者，收到许可证后粘贴并验证即可解锁。", choose: "1. 选择要购买的皮肤", device: "2. 复制设备码给开发者", license: "3. 粘贴许可证", copy: "复制", copied: "已复制", loadingCode: "正在生成设备码…", codeUnavailable: "设备码暂时不可用", copyFailed: "复制失败，请重试。", owned: "拥有", placeholder: "粘贴完整的许可证 JSON", activate: "验证许可证", working: "正在验证…", ready: "选择想购买的皮肤并发送设备码；实际启用皮肤请在系统托盘的主题菜单操作。", verifying: "正在验证许可证与当前设备，请稍候。", activated: "许可证验证成功，已解锁对应皮肤。请在系统托盘主题菜单中启用。", failed: "许可证验证失败，请稍后重试。" }, en: { title: "Supporter skins", description: "Choose the skin you want to buy, send its device code to the developer, then paste and verify the license to unlock it.", choose: "1. Choose a skin to purchase", device: "2. Copy this device code for the developer", license: "3. Paste your license", copy: "Copy", copied: "Copied", loadingCode: "Generating device code…", codeUnavailable: "Device code is temporarily unavailable", copyFailed: "Copy failed. Try again.", owned: "Owned", placeholder: "Paste the complete license JSON", activate: "Verify license", working: "Verifying…", ready: "Choose a skin to purchase. Enable unlocked skins from the system-tray Theme menu.", verifying: "Verifying the license for this device…", activated: "License verified. Enable the unlocked skin from the system-tray Theme menu.", failed: "License verification failed. Try again shortly." } } as const;
const choices: Array<{ id: Exclude<WidgetSkin, "default">; name: Record<Language, string>; price: string; thumbnail?: string }> = [{ id: "blur", name: { "zh-CN": "Blur", en: "Blur" }, price: "¥1.99", thumbnail: blurThumbnailUrl }, { id: "computer", name: { "zh-CN": "Computer", en: "Computer" }, price: "¥3.99" }];
const previewStatus: SupporterStatus = { requestCode: "QF1-C4948F12-A7D75558-9D800D0F-5DDB5E9A", active: true, message: "Supporter licenses are active.", unlockedSkin: "blur", unlockedSkins: ["blur", "computer"], selectedSkin: "blur", availableSkins: ["default", "blur", "computer"] };

export function SupporterPanel({ onStatus, preview = false, celebrationKey = 0 }: { onStatus: (status: SupporterStatus) => void; preview?: boolean; celebrationKey?: number }) {
  const [status, setStatus] = useState<SupporterStatus | null>(null); const [requestedSkin, setRequestedSkin] = useState<Exclude<WidgetSkin, "default">>("blur"); const [license, setLicense] = useState(""); const [busy, setBusy] = useState(false); const [copied, setCopied] = useState(false); const [language, setLanguage] = useState<Language>("zh-CN"); const [message, setMessage] = useState(""); const [statusError, setStatusError] = useState(false); const [showLike, setShowLike] = useState(false); const t = labels[language];
  useEffect(() => { if (preview) { setStatus(previewStatus); return; } void getSupporterStatus().then((value) => { setStatus(value); setStatusError(false); onStatus(value); }).catch(() => setStatusError(true)); }, [preview]);
  useEffect(() => { void getPreferences().then((value) => setLanguage(normalizeLanguage(value.language))); let cleanup = () => {}; void listenDesktopEvents({ onPreferences: (value) => setLanguage(normalizeLanguage(value.language)), onRefresh: () => {}, onUpdate: () => {} }).then((unlisten) => { cleanup = unlisten; }); return () => cleanup(); }, []);
  const celebrate = () => { setShowLike(false); window.requestAnimationFrame(() => setShowLike(true)); window.setTimeout(() => setShowLike(false), 1_600); };
  useEffect(() => { if (celebrationKey > 0) celebrate(); }, [celebrationKey]);
  const activate = () => { if (!license.trim()) return; setBusy(true); setMessage(t.verifying); void activateSupporterLicense(license).then((value) => { setStatus(value); onStatus(value); setLicense(""); setMessage(t.activated); celebrate(); }).catch(() => setMessage(t.failed)).finally(() => setBusy(false)); };
  const deviceCode = status?.requestCode;
  const copyCode = () => { if (!deviceCode) return; void navigator.clipboard.writeText(deviceCode).then(() => { setCopied(true); window.setTimeout(() => setCopied(false), 1800); }).catch(() => setMessage(t.copyFailed)); };
  return <main className="supporter-panel" aria-label={t.title}>{showLike ? <img className="supporter-like-burst" src={likeIconUrl} alt="" aria-hidden="true" /> : null}<header className="supporter-brand"><div className="supporter-logo"><img src={logoUrl} alt="Quota Float" /><span>Quota-float</span></div></header><h1>{t.title}</h1><p className="supporter-description">{t.description}</p><section className="supporter-workflow"><h2>操作</h2><div className="supporter-step"><span>{t.choose}</span><div className="supporter-skins">{choices.map((skin) => { const owned = status?.availableSkins.includes(skin.id) ?? false; return <button key={skin.id} type="button" disabled={busy} className={`${requestedSkin === skin.id ? "is-selected" : ""}${owned ? " is-owned" : ""}`} aria-pressed={requestedSkin === skin.id} onClick={() => setRequestedSkin(skin.id)}><i className="skin-choice-dot" /><span className="skin-choice-copy"><b>{skin.name[language]}</b><small>{skin.price}</small></span>{owned ? <em className="skin-owned-badge">{t.owned}</em> : null}{skin.thumbnail ? <img src={skin.thumbnail} alt="" /> : <span className="computer-skin-thumbnail" />}</button>; })}</div></div><div className="supporter-step"><span>{t.device}</span><div className="supporter-code"><code>{deviceCode ?? (statusError ? t.codeUnavailable : t.loadingCode)}</code><button type="button" disabled={!deviceCode} onClick={copyCode} aria-live="polite">{copied ? t.copied : t.copy}</button></div></div><label className="supporter-step"><span>{t.license}</span><textarea value={license} onChange={(event) => setLicense(event.target.value)} placeholder={t.placeholder} rows={4} /></label></section><button type="button" className="supporter-primary" disabled={busy || !license.trim()} onClick={activate}>{busy ? t.working : t.activate}</button><p className="supporter-status" role="status">{message || t.ready}</p><section className="supporter-legal" aria-label={language === "zh-CN" ? "许可提示" : "License notice"}><strong>{language === "zh-CN" ? "许可与使用提醒" : "License and use reminder"}</strong><p>{language === "zh-CN" ? "许可证与当前设备码绑定，请妥善保管并勿公开分享。验证仅解锁支持者皮肤，不影响额度数据或账户权限；额度、登录和服务状态由相关服务提供，重要信息建议以官方页面为准并自行确认。如需更换设备或协助，请携带设备码联系支持者。" : "Licenses are tied to the displayed device code, so please keep them private. Verification unlocks the supporter skin only and does not change quota data or account permissions. Quota, sign-in, and service status come from the relevant services; please confirm important information with the official source. For a new device or assistance, contact support with its device code."}</p></section><footer className="supporter-designer">Designer <span>@Change</span></footer></main>;
}
